[package]
name = "torrenting"
version = "0.1.0"
edition = "2024"

[dependencies]
bip_bencode = "0.4.4"
hex = "0.4.3"
lava_torrent = "0.11.1"
native-tls = "0.2.14"
percent-encoding = "2.3.2"
thiserror = "2.0.16"
url = "2.5.7"
tokio = { version = "1", features = ["full"] }
